name: Adapt Bug Report
description: File a bug report for Adapt
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out!
        If this does not work for you, feel free to use the [blank](https://github.com/VolmitSoftware/Adapt/issues/new) format.
  - type: textarea
    id: how
    attributes:
      label: Problem
      description: Please give a text description of how you reached the problem
      value: |
        1. Install Adapt...
        2. Do this...
        3. Do that...
        4. Observe the error...
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Solution (if any)
      description: Explain where you think the problem comes from (optional)
      placeholder: The code to place a is missing b and c...
    validations:
      required: false
  - type: dropdown
    id: mcversion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft is the server on?
      options:
        - 1.18
        - 1.19
        - 1.20
        - 1.21
        - 1.22
    validations:
      required: true
  - type: input
    id: Adaptversion
    attributes:
      label: Adapt Version
      description: What version of Adapt are you running?
      placeholder: DO NOT SAY "LATEST"
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log
      description: Paste a full log. Always use [mclogs](https://mclo.gs) Or [Pastebin](https://pastebin.com/). Must not be a crash report. Must be a full log. Must not be a screenshot of a log.
      placeholder: https://mslog.gs/...
    validations:
      required: true
  - type: markdown
    id: thanks
    attributes:
      value: "Thank you for filling out the form! We will be with you soon. Please do not ask support to review your report."
