package art.arcane.edict.api.input;

import art.arcane.edict.api.parser.EdictValue;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Singular;

import java.util.List;

/**
 * The MappedEdictInputHolder class implements both the EdictInput and MappedInput interfaces,
 * representing a type of EdictInput that is mapped to a key in the Edict command handling system.
 * <br><br>
 * Each instance of this class holds the key to which the input is mapped and a list of parsed
 * values, which are the results of parsing the input string with respect to the command's requirements.
 */
@Data
@AllArgsConstructor
@Builder
public class MappedEdictInputHolder implements EdictInput, MappedInput {

    /**
     * The 'key' field represents the unique identifier to which the input is mapped.
     * This is used as a reference point for the command's input structure.
     */
    private final String key;

    /**
     * The 'parsedValues' field holds a list of EdictValue objects, which are generated by parsing
     * the corresponding input string. Each EdictValue object represents a potential interpretation
     * of the input, along with an associated confidence level.
     */
    @Singular
    private final List<EdictValue<?>> parsedValues;
}
