/*
 *  Copyright (c) 2016-2025 Arcane Arts (Volmit Software)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 */

package art.arcane.edict.api.input;

import art.arcane.edict.api.parser.EdictValue;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Singular;

import java.util.List;

/**
 * The MappedEdictInputHolder class implements both the EdictInput and MappedInput interfaces,
 * representing a type of EdictInput that is mapped to a key in the Edict command handling system.
 * <br><br>
 * Each instance of this class holds the key to which the input is mapped and a list of parsed
 * values, which are the results of parsing the input string with respect to the command's requirements.
 */
@Data
@AllArgsConstructor
@Builder
public class MappedEdictInputHolder implements EdictInput, MappedInput {

    /**
     * The 'key' field represents the unique identifier to which the input is mapped.
     * This is used as a reference point for the command's input structure.
     */
    private final String key;

    /**
     * The 'parsedValues' field holds a list of EdictValue objects, which are generated by parsing
     * the corresponding input string. Each EdictValue object represents a potential interpretation
     * of the input, along with an associated confidence level.
     */
    @Singular
    private final List<EdictValue<?>> parsedValues;
}
