package art.arcane.react.localization;

import art.arcane.volmlib.util.localization.LanguageFileHeader;

import art.arcane.volmlib.util.localization.LanguageReferenceRenderer;

import java.util.List;
import java.util.Map;

final class ReactLanguageReference {
  private ReactLanguageReference() {
  }

  static String englishCatalog() {
    return LanguageReferenceRenderer.render(ReactMessages.catalog(), header(ReactMessages.catalog().englishLocale()));
  }

  static List<String> header(String locale) {
      return LanguageFileHeader.render(new LanguageFileHeader.Options(
              "React", locale,
              List.of("runtime.prefix is added before prefixed chat messages."),
              List.of(
                      "Chat messages support & color codes: &cText&r, &lText&r.",
                      "Colors: &0-&9 and &a-&f.",
                      "Styles: &l bold, &o italic, &n underline, &m strikethrough, &k obfuscated, &r reset.",
                      "Color codes clear active styles; put color before styles, as in &3&lText&r. &r resets all formatting.",
                      "RGB colors use &#RRGGBBText&r, for example &#55AAFFText&r.",
                      "Use MiniMessage for gradients and interactions; do not mix MiniMessage tags and & codes in one message. Close tags in reverse opening order.",
                      "Keep TOML quotes and escapes valid.",
                      "Use \\n in quoted TOML strings for a new line; {{ and }} display literal braces.",
                      "renderer.* and config.documentation.annotation.* values are plain text.",
                      "test.* values are plain text except test.result.* messages, which support formatting.",
                      "Keep placeholders in message text, outside MiniMessage tags."
              ),
              Map.ofEntries(
                      Map.entry("action", "Action name or color adjustment direction"),
                      Map.entry("actions", "Queued action count or list of excluded action names"),
                      Map.entry("active", "Number of active features or tweaks"),
                      Map.entry("actor", "Web user who made a change"),
                      Map.entry("added", "Whether a feature rejoined the active registry after activation"),
                      Map.entry("after", "Configuration value, language message, or heap usage after a change"),
                      Map.entry("age", "Age of integration data in seconds"),
                      Map.entry("amount", "Number of items to give"),
                      Map.entry("architecture", "CPU architecture"),
                      Map.entry("argument", "Unexpected command argument"),
                      Map.entry("available", "Number of available NMS bridge handles"),
                      Map.entry("average", "Average TPS or milliseconds per tick"),
                      Map.entry("avg_mspt", "Average milliseconds per tick during a load-test pass"),
                      Map.entry("avg_tps", "Average ticks per second during a load-test pass"),
                      Map.entry("bar", "Formatted benchmark score bar"),
                      Map.entry("before", "Configuration value, language message, or heap usage before a change"),
                      Map.entry("checked", "Number of samplers checked"),
                      Map.entry("chunks", "Number of chunks affected by an action"),
                      Map.entry("code", "Web pairing code"),
                      Map.entry("command", "Command path"),
                      Map.entry("count", "Number of entries, modules, changes, or test findings"),
                      Map.entry("current", "Current page number"),
                      Map.entry("delta_heap", "Difference in ending heap usage between React and baseline, in MB"),
                      Map.entry("delta_mspt", "Difference in average tick time between React and baseline, in ms"),
                      Map.entry("delta_tps", "Difference in average TPS between React and baseline"),
                      Map.entry("detail", "Bridge, integration, action, or test diagnostic details"),
                      Map.entry("dimensions", "Detected map-wall grid dimensions"),
                      Map.entry("direction", "Direction to rotate the selected color's hue"),
                      Map.entry("distance", "Requested view, simulation, or send distance in chunks"),
                      Map.entry("duration", "Elapsed time; load-test start messages use seconds"),
                      Map.entry("enabled", "Enabled state or number of enabled modules"),
                      Map.entry("entities", "Number of entities affected by an action"),
                      Map.entry("entry", "Integration timeline entry"),
                      Map.entry("exceptions", "React exceptions recorded during a load-test pass"),
                      Map.entry("fail", "Number of failed checks"),
                      Map.entry("file", "Configuration, language, or plugin API file name"),
                      Map.entry("fingerprint", "Server or web token fingerprint"),
                      Map.entry("finite", "Number of samplers returning finite values"),
                      Map.entry("frames", "Number of item frames in the active map wall"),
                      Map.entry("free", "Free physical or virtual memory"),
                      Map.entry("freed", "Heap memory reclaimed by garbage collection"),
                      Map.entry("from", "First entry number on the current page"),
                      Map.entry("grid", "Map-wall grid dimensions"),
                      Map.entry("ground_y", "Ground height for the gravity test"),
                      Map.entry("group", "Monitor, sampler, map, configuration, or language-message group"),
                      Map.entry("growth", "Heap growth during a load test, in MB"),
                      Map.entry("health", "Integration health state"),
                      Map.entry("heap_end", "Heap usage at the end of a load-test pass, in MB"),
                      Map.entry("heap_start", "Heap usage at the start of a load-test pass, in MB"),
                      Map.entry("heartbeat", "Time since the integration's latest heartbeat"),
                      Map.entry("height", "Test canvas height in pixels"),
                      Map.entry("hoppers", "Number of hoppers normalized"),
                      Map.entry("id", "Bridge handle, sampler, map, action, pack, or token identifier"),
                      Map.entry("impact", "Configuration effect description or plugin cost in ms/s"),
                      Map.entry("incident", "Identifier of the recursive incident action excluded from the dev suite"),
                      Map.entry("index", "Current dev-suite step number"),
                      Map.entry("invalid", "Number of samplers with invalid readings"),
                      Map.entry("issued_at", "Web token creation time"),
                      Map.entry("item", "Item name or identifier"),
                      Map.entry("items", "Number of item entities merged"),
                      Map.entry("key", "Command parameter key, configuration key, or language message ID"),
                      Map.entry("label", "Benchmark, metric, setting, command, or web token label"),
                      Map.entry("line", "Line number being edited in a multi-line message"),
                      Map.entry("lines", "Number of server log lines scanned"),
                      Map.entry("loaded", "Number of chunks newly loaded during prewarming"),
                      Map.entry("locale", "Language code being displayed, selected, or edited"),
                      Map.entry("matched", "Worlds whose autosave state matches the test baseline"),
                      Map.entry("max_tick", "Longest observed tick gap during a load test, in ms"),
                      Map.entry("maximum", "Maximum item count, tick-time threshold, or editor input length"),
                      Map.entry("message", "Completed action summary or integration status message"),
                      Map.entry("metrics", "Number of metrics supplied by a plugin API pack"),
                      Map.entry("minecraft", "Minecraft version"),
                      Map.entry("minimum", "Minimum acceptable TPS"),
                      Map.entry("missing", "Number of required samplers missing from the registry"),
                      Map.entry("mode", "Selected game mode or ability mode"),
                      Map.entry("model", "CPU model"),
                      Map.entry("name", "Benchmark, module, renderer, or test check name"),
                      Map.entry("note", "Reason the server log was not scanned"),
                      Map.entry("offenders", "Number of samplers returning non-finite values"),
                      Map.entry("operations", "Ability callback operations per minute"),
                      Map.entry("options", "Accepted configuration values"),
                      Map.entry("p95", "95th-percentile tick time during a load test, in ms"),
                      Map.entry("parameter", "Command parameter name"),
                      Map.entry("parameters", "Command parameters that were ignored"),
                      Map.entry("pass", "Number of passed checks"),
                      Map.entry("path", "Configuration key path or report file path"),
                      Map.entry("percent", "Color adjustment percentage or plugin impact share"),
                      Map.entry("permission", "Required permission node"),
                      Map.entry("personal", "Player's selected language code"),
                      Map.entry("phase", "Feature lifecycle phase being tested"),
                      Map.entry("pixels", "Number of non-blank pixels rendered by a map test"),
                      Map.entry("platform", "Operating system or Minecraft server platform"),
                      Map.entry("players", "Number of synthetic players in a load test"),
                      Map.entry("plugin", "Plugin name"),
                      Map.entry("process_load", "CPU load of the server process"),
                      Map.entry("processors", "Number of available CPU processors"),
                      Map.entry("profile", "React configuration profile name"),
                      Map.entry("protocol", "Integration protocol version"),
                      Map.entry("radius", "Chunk radius for a map or dev-suite action"),
                      Map.entry("range", "Accepted view, simulation, or send distance range in chunks"),
                      Map.entry("rate", "Configured crop fast-forward rate"),
                      Map.entry("rating", "Formatted benchmark rating"),
                      Map.entry("react_errors", "Number of React error lines found in the server log"),
                      Map.entry("reason", "Failure, rejection, or unavailable-state explanation"),
                      Map.entry("registered", "Number of registered modules"),
                      Map.entry("removed_first", "Whether initial deactivation removed a feature from the active registry"),
                      Map.entry("removed_second", "Whether repeated deactivation removed a feature from the active registry"),
                      Map.entry("renderer", "Map renderer name or identifier"),
                      Map.entry("renderers", "List of map renderers with blank identifiers"),
                      Map.entry("role", "Web access role: viewer, operator, or admin"),
                      Map.entry("sampler", "Sampler name or identifier"),
                      Map.entry("samplers", "List of integration or failing samplers"),
                      Map.entry("scope", "Map scope or distance-setting scope"),
                      Map.entry("score", "Benchmark score"),
                      Map.entry("seconds", "Countdown or load-test duration in seconds"),
                      Map.entry("section", "Configuration section name"),
                      Map.entry("server", "Minecraft server implementation and version"),
                      Map.entry("shown", "Number of rows currently displayed"),
                      Map.entry("since_run", "Errors reported since the current test started"),
                      Map.entry("size", "Maximum or active map-wall dimensions"),
                      Map.entry("skip", "Number of skipped checks"),
                      Map.entry("spawn_y", "Height where the gravity-test block was spawned"),
                      Map.entry("state", "Action or plugin API pack state"),
                      Map.entry("status", "Integration status or configuration state label"),
                      Map.entry("subject", "Module or setting described by configuration help"),
                      Map.entry("subsystem", "Test subsystem name"),
                      Map.entry("summary", "Action audit summary"),
                      Map.entry("system_load", "CPU load of the whole system"),
                      Map.entry("target", "World, player, plugin, setting, or plugin group targeted by an operation"),
                      Map.entry("threading", "Server threading mode"),
                      Map.entry("tick", "Tick duration that exceeded the freeze threshold, in ms"),
                      Map.entry("tick_crashes", "Number of tick-crash lines found in the server log"),
                      Map.entry("tier", "Incident playbook severity tier"),
                      Map.entry("timing", "Ability callback time in milliseconds per minute"),
                      Map.entry("to", "Last entry number on the current page"),
                      Map.entry("total", "Total entries, modules, worlds, checks, or memory in the message"),
                      Map.entry("type", "Command parameter, configuration value, map, or distance type"),
                      Map.entry("unavailable", "Number of unavailable NMS bridge handles"),
                      Map.entry("unit", "Unit label for a pie-chart total"),
                      Map.entry("unknown", "Identifier of the unknown action excluded from the dev suite"),
                      Map.entry("unreadable", "Number of samplers that could not be read"),
                      Map.entry("uptime", "Host operating-system uptime"),
                      Map.entry("url", "Uploaded diagnostic report URL"),
                      Map.entry("usage", "Command usage syntax"),
                      Map.entry("used", "Used physical memory, virtual memory, or heap"),
                      Map.entry("value", "Formatted setting, measurement, or hardware detail"),
                      Map.entry("values", "Sampled values listed in a dev-suite report"),
                      Map.entry("variables", "Placeholder names accepted by the message being edited"),
                      Map.entry("vendor", "Java vendor"),
                      Map.entry("verdict", "Overall test verdict"),
                      Map.entry("version", "React, Java, or platform version"),
                      Map.entry("warmed", "Number of chunks prewarmed"),
                      Map.entry("warn", "Number of checks with warnings"),
                      Map.entry("width", "Test canvas width in pixels"),
                      Map.entry("world", "Minecraft world name")
              )));
  }
}
