name: ${name}
main: art.arcane.react.React
version: ${version}
folia-supported: true
authors: [ NextdoorPsycho, Cyberpwn ]
api-version: ${apiversion}
commands:
  react:
    aliases: [ re ]
permissions:
  react.use:
    description: Allows using the /react command root.
    default: op
  react.*:
    description: Allows using all /react commands.
    default: op
    children:
      react.use: true
