name: ${name}
main: com.volmit.react.React
version: ${version}
authors: [ NextdoorPsycho, Cyberpwn ]
api-version: ${apiversion}
commands:
  react:
    aliases: [ re ]
libraries:
  - net.kyori:adventure-text-minimessage:4.24.0
  - net.kyori:adventure-platform-bukkit:4.4.1
  - net.kyori:adventure-api:4.9.3
  - io.timeandspace:smoothie-map:2.0.2
  - it.unimi.dsi:fastutil:8.5.8
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.10
  - org.zeroturnaround:zt-zip:1.15
  - org.bitbucket.mstrobel:procyon-core:0.6.0
  - org.bitbucket.mstrobel:procyon-compilertools:0.6.0
  - org.bitbucket.mstrobel:procyon-reflection:0.6.0
  - fr.inria.gforge.spoon:spoon-core:10.2.0
  - com.github.ben-manes.caffeine:caffeine:3.0.6
  - org.java-websocket:Java-WebSocket:1.5.3
